name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm ci

    - name: Set Config Variables
      run: |
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} APP_HOST="${{ vars.HOST }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} TWILIO_ACCOUNT_SID="${{ secrets.TWILIO_ACCOUNT_SID }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} TWILIO_AUTH_TOKEN="${{ secrets.TWILIO_AUTH_TOKEN }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} TWILIO_WHATSAPP_PHONE_NUMBER="${{ vars.TWILIO_WHATSAPP_PHONE_NUMBER }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} OPENAI_CHAT_GPT="${{ secrets.OPENAI_CHAT_GPT }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} STRIPE_PAYMENT_LINK="${{ vars.STRIPE_PAYMENT_LINK }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} STRIPE_API_KEY="${{ secrets.STRIPE_API_KEY }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} STRIPE_SIGNING_SECERT="${{ secrets.STRIPE_SIGNING_SECERT }}"
        heroku config:set -a ${{ vars.HEROKU_APP_NAME }} CONTACT_EMAIL="${{ vars.CONTACT_EMAIL }}"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ vars.HEROKU_APP_NAME }}
        heroku_email: ${{ vars.HEROKU_EMAIL }}
        buildpack: "heroku/nodejs"
